### ISSUE TITLE
[Tracking Issue] Cleanup for version 4.4.0

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1606]
Tracking items to clean up for 4.4.0:

- [ ]  Add docs for RTDB pagination
- [x] Check out sample UI and consistency for RTDB pagination
- [ ] Update dependencies to latest non-breaking Firebase versions

**Comment by samtstern** [comment]
Fixed by #1635
